### ISSUE TITLE
15. Bug: Como usuario, quiero marcar un artículo de mi lista de la compra como comprado para que la aplicación pueda saber con qué frecuencia compro diferentes artículos.

### ISSUE THREAD

**Issue by alxmcr** [the-collab-lab/tcl-34-smart-shopping-list#27]
Bug 🐞 :
Sucede cuando tienes un producto marcado como "comprado" (checkbox como `checked` ✔️ ), como usuario tienes todavía la posibilidad de "volver a marcar como comprado" un producto, sin importar si ya paso al menos un día y esto impacta/actualiza la base de datos. Lo cual no es un comportamiento esperado. Incluso, si realizas un check la primera vez, genera un error relacionado al input & custom input. (ver videos)

Related issues: #8

https://user-images.githubusercontent.com/8689897/140624544-f039e2df-48c0-4294-b374-c8a20d875151.mp4

https://user-images.githubusercontent.com/8689897/140624648-ec736af7-f802-4b2a-884b-dce6bef35a75.mp4

**Comment by yanurd** [comment]
@alxmcr Sobre esto, tengo entendido que el check debe persistir 24 horas, lo que me hace pensar que durante 24 h siempre estará check (así lo hicimos en la semana pasada @IsabellaSoares y yo ) ¿Será que entendimos mal? 🥺☠️😅🤡

**Comment by alxmcr** [comment]
@yanurd Lo que comentas, está bien. Sin embargo, hay un detalle el "checkbox" debería estar checked, pero también "deshabilitado" mientras dure esas 24 horas. Debido, a que se supone que ya compraste el producto y no necesitarías comprarlo nuevamente. Por lo tanto, no deberíamos permitir hacer un check en cualquier momento, marcar una "compra" sin necesidad y evitar modificar la base de datos cuando no lo requerimos.

En resumen: la funcionalidad básica está bien, pero faltaría en mi opinión deshabilitar el hacer check en el checkbox en los momentos correctos. Actualmente, hay un comportamiento débil en ese aspecto.
