### ISSUE TITLE
16. Como usuario, quiero poder borrar el campo del nombre del producto cuando voy a crear un nuevo producto.

### ISSUE THREAD

**Issue by IsabellaSoares** [the-collab-lab/tcl-34-smart-shopping-list#42]
AC:

- Cuando el campo del nombre del produto tiene texto, el usuario debe poder tocar un elemento de la interfaz de usuario (por ejemplo, con un botón "X" junto al campo) para limpiar el campo.

Notas:

- Esta funcionalidad ya existe en el campo de filtro.

**Comment by yanurd** [comment]
Si la funcionalidad existe ya en el campo del filtro, quizás sea idóneo extraerla como una funcion en utils para poder reutilizarla.
